micronaut:
  server:
    port: 8081
  application:
    name: test_auth
  security:
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: http://localhost:8080/realms/sadhak/protocol/openid-connect/certs
  endpoints:
    keys:
      enabled: true
      path: keys
    introspection:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
